require("dotenv").config();
const http = require("http");
const express = require("express");
const cors = require("cors");
const helmet = require("helmet");
const rateLimit = require("express-rate-limit");
const cookieParser = require("cookie-parser");
const morgan = require("morgan");
const swaggerUi = require("swagger-ui-express");
const yaml = require("js-yaml");
const fs = require("fs");
const path = require("path");
const { authRouter } = require("./routes/auth.routes");
const { ticketRouter } = require("./routes/ticket.routes");
const { dashboardRouter } = require("./routes/dashboard.routes");
const { userRouter } = require("./routes/user.routes");
const { notificationRouter } = require("./routes/notification.routes");
const { notFound, errorHandler } = require("./middleware/error");
const app = express();
app.use(helmet());
app.use(cors({ origin: process.env.FRONTEND_URL, credentials: true }));
app.use(express.json({ limit: "2mb" }));
app.use(cookieParser());
app.use(morgan("combined"));
app.use(rateLimit({ windowMs: 15 * 60 * 1000, max: 500 }));
app.use("/uploads", express.static("uploads"));
app.get("/health", (_, res) => res.json({ status: "ok" }));
app.use("/api/auth", authRouter);
app.use("/api/tickets", ticketRouter);
app.use("/api/dashboard", dashboardRouter);
app.use("/api/users", userRouter);
app.use("/api/notifications", notificationRouter);
const openapiPath = path.join(__dirname, "..", "openapi.yaml");
if (fs.existsSync(openapiPath)) { app.use("/docs", swaggerUi.serve, swaggerUi.setup(yaml.load(fs.readFileSync(openapiPath, "utf8")))); }
app.use(notFound);
app.use(errorHandler);
const port = Number(process.env.PORT || 8080);
http.createServer(app).listen(port, () => console.log(`API listening on ${port}`));
